# Generated by Django 4.1.7 on 2023-03-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='username',
            field=models.CharField(default='default', max_length=120, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
